export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const SET_LOADING = "SET_LOADING";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const GET_CUSTOMER = "GET_CUSTOMER";
